### ISSUE TITLE
Push fails

### ISSUE THREAD

**Issue by calind** [PressLabs/gitium#67] opened 2015-01-23 09:52 UTC
The local code is behind 1 commit. When hitting the webhook, push fails:
```
PHP User Error:  push failed! <pre>error: failed to push some refs to 'ssh://git@git.presslabs.net/XXX.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again.  See the 'Note about fast-forwards' section of 'git push --help' for details. To ssh://git@git.presslabs.net/olwomen.git !	refs/heads/master:refs/heads/master	[rejected] (non-fast-forward) Done</pre> in /www/presslabs/git-webhook.php on line 23 when calling trigger_error(), request: GET /git-webhook.php, request_id: b82c40225504d270610a1f08c2d242c7
```

**Comment by pdobrescu** [comment] 2015-10-22 10:33
Duplicate of https://github.com/PressLabs/gitium/issues/30

**Closed by pdobrescu** 2015-10-22 10:33 UTC
Labels: bug
