### ISSUE TITLE
.gitignore is being ignored

### ISSUE THREAD

**Issue by Bananenbaas** [presslabs/gitium#125] opened 2016-10-25 11:41 UTC
Hi, 

We are using your plugin and are planning to use it on more websites. But in our development area the plugin keeps writing the wp-config.php and errorlogs to bitbucket. We've put the file names into .gitignore, but they are still being committed to bitbucket...

**Comment by Marius786** [comment] 2016-11-04 12:40
Hello @Bananenbaas, can you give more details:
- what errors do you get in error logs related to the .gitignore file, if you add/remove some line from /wp-admin/admin.php?page=gitium%2Fgitium-settings.php?
- what kind of webserver do you have(linux/windows based)?

**Comment by DenisFlorin** [comment] 2024-12-06 10:20
As the reporter did not provide any feedback, I am closing this case. Despite my recent testing with Bitbucket, I was unable to reproduce the mentioned issue.

**Closed by DenisFlorin** 2024-12-06 10:20 UTC
