### ISSUE TITLE
Fast forward error

### ISSUE THREAD

**Issue by milero** [PressLabs/gitium#103] opened 2016-05-12 13:01 UTC
PHP User Error:  push failed! <pre>error: failed to push some refs to '***.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again.  See the 'Note about fast-forwards' section of 'git push --help' for details. To ***.git !    refs/heads/master:refs/heads/master    [rejected] (non-fast-forward) Done</pre> in ***.php on line 23 when calling trigger_error(), request: GET ***.php, request_id: 1f4e1841a4e6cc4e8156b0b0cd8968fb

**Comment by calind** [comment] 2016-05-20 12:40
Duplicate of #94.

**Closed** 2016-05-20 12:40 UTC
