### ISSUE TITLE
On deleting Gitium, the .git directory is not deleted along with the plugin files

### ISSUE THREAD

**Issue by mariusveltan** [PressLabs/gitium#77] opened 2015-06-17 14:30 UTC
I have the following scenario: installed Gitium on a WordPress site, entered the Git repo URL and hit Fetch. The PHP connection timed-out while fetching.

In consequence, the theme files were not cloned from the Git repo, but the .git directory was created and WP options set.

As a result, the clone is incomplete, but Gitium appears linked to the Git repo. Merge/Pull does not work. 

When trying to reset Gitium, deactivating and deleting the plugin, together with clearing the Gitium options from the database is not a solution since, upon activating a fresh install of the plugin, the Gitium options are recreated based on the content of the .git directory - from what I understand.

An idea would be to add an Uninstall option, which clears the DB and the .git directory.

**Comment by calind** [comment] 2015-12-18 15:22
I would rather implement a "Disconnect" button with a big warning screen.

**Comment by calind** [comment] 2015-12-18 15:23
Closing this as a duplicate of #49.

**Closed** 2015-12-18 15:23 UTC
